# Generated by Django 4.2.4 on 2023-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imágen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'Libro',
            },
        ),
    ]
