name: CI - Django CRUD Libros

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y default-libmysqlclient-dev zip
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas (simuladas)
      run: |
        echo "Simulaci칩n de pruebas autom치ticas"

    - name: Comprimir c칩digo fuente
      run: |
        zip -r django_project.zip . -x "**/__pycache__/*" "**/*.pyc" "**/.git/*" "venv/*"

    - name: Subir artifact al job
      uses: actions/upload-artifact@v4
      with:
        name: django-crud-zip
        path: django_project.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Descargar artifact
      uses: actions/download-artifact@v3
      with:
        name: django-crud-zip
        path: .

    - name: Crear Release
      uses: softprops/action-gh-release@v2
      with:
        files: django_project.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}